version: '2'
services:
  app:
    build: .
    environment:
      RAILS_ENV: development
      DATABASE_URL: mysql2://root:pass@mysql:3306
      MYSQL_ROOT_PASSWORD: 'pass'
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/WaitQueueProject
        # .dockerignoreに今は記載済み。どちらが良いか判別つかないため一旦コメントアウト
        # exclude volumes(空のhogeをマウントさせる)
#      - hoge:/usr/src/WaitQueueProject/app/vendor
#      - hoge:/usr/src/WaitQueueProject/app/tmp
#      - hoge:/usr/src/WaitQueueProject/app/log
#      - hoge:/usr/src/WaitQueueProject/app/.git
#      - hoge:/usr/src/WaitQueueProject/db_init
    links:
      - mysql
  mysql:
    image: mysql:5.7.10
    environment:
      MYSQL_ROOT_PASSWORD: 'pass'
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db_init:/docker-entrypoint-initdb.d
volumes:
  mysql-data:
    driver: local
  hoge:
